# Site settings
name: 蛋花的技术栈
email: zthreefires@gmail.com
author: sanhuo zhang
url: https://zthreefires.github.io/
#个人简历地址
resume_site: https://zthreefires.github.io/
github: https://github.com/zthreefires/
baseurl: ""
description: IoT + AI
meta_description: 
motto: 
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: zthreefires

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

